<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RaceResultSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('race_results')->insert([
            ['grand_prix_id' => 1, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 1, 'grid' => 1, 'laps' => 57, 'time_or_retired' => '1:31:44.742', 'points' => 26.0, 'fastest_lap' => true],
            ['grand_prix_id' => 1, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 2, 'grid' => 5, 'laps' => 57, 'time_or_retired' => '+22.457s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 3, 'grid' => 4, 'laps' => 57, 'time_or_retired' => '+25.110s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 4, 'grid' => 2, 'laps' => 57, 'time_or_retired' => '+39.669s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 5, 'grid' => 3, 'laps' => 57, 'time_or_retired' => '+46.788s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 6, 'grid' => 7, 'laps' => 57, 'time_or_retired' => '+48.458s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 7, 'grid' => 9, 'laps' => 57, 'time_or_retired' => '+50.324s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 8, 'grid' => 8, 'laps' => 57, 'time_or_retired' => '+56.082s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 9, 'grid' => 6, 'laps' => 57, 'time_or_retired' => '+1:14.887', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 10, 'grid' => 12, 'laps' => 57, 'time_or_retired' => '+1:33.216', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 11, 'grid' => 17, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 12, 'grid' => 15, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 13, 'grid' => 14, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 14, 'grid' => 11, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 15, 'grid' => 13, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 16, 'grid' => 10, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 17, 'grid' => 16, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 18, 'grid' => 18, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 19, 'grid' => 19, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 1, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 20, 'grid' => 20, 'laps' => 55, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 2, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 1, 'grid' => 1, 'laps' => 50, 'time_or_retired' => '1:20:43.273', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 2, 'grid' => 3, 'laps' => 50, 'time_or_retired' => '+13.643s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 3, 'grid' => 2, 'laps' => 50, 'time_or_retired' => '+18.639s', 'points' => 16.0, 'fastest_lap' => true],
            ['grand_prix_id' => 2, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 4, 'grid' => 4, 'laps' => 50, 'time_or_retired' => '+23.625s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 5, 'grid' => 6, 'laps' => 50, 'time_or_retired' => '+26.522s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 6, 'grid' => 7, 'laps' => 50, 'time_or_retired' => '+35.747s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 21, 'constructor_id' => 2, 'position' => 7, 'grid' => 11, 'laps' => 50, 'time_or_retired' => '+47.391s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 8, 'grid' => 8, 'laps' => 50, 'time_or_retired' => '+48.626s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 9, 'grid' => 5, 'laps' => 50, 'time_or_retired' => '+49.756s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 10, 'grid' => 10, 'laps' => 50, 'time_or_retired' => '+55.173s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 11, 'grid' => 13, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 12, 'grid' => 14, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 13, 'grid' => 15, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 14, 'grid' => 12, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 15, 'grid' => 16, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 16, 'grid' => 17, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 17, 'grid' => 18, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 18, 'grid' => 19, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 19, 'grid' => 20, 'laps' => 48, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 2, 'driver_id' => 11, 'constructor_id' => 6, 'position' => null, 'grid' => 9, 'laps' => 6, 'time_or_retired' => 'DNF - gearbox', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 3, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 1, 'grid' => 2, 'laps' => 58, 'time_or_retired' => '1:20:26.843', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 2, 'grid' => 5, 'laps' => 58, 'time_or_retired' => '+2.366s', 'points' => 19.0, 'fastest_lap' => true],
            ['grand_prix_id' => 3, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 3, 'grid' => 3, 'laps' => 58, 'time_or_retired' => '+5.904s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 4, 'grid' => 4, 'laps' => 58, 'time_or_retired' => '+35.770s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 5, 'grid' => 6, 'laps' => 58, 'time_or_retired' => '+56.309s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 6, 'grid' => 7, 'laps' => 58, 'time_or_retired' => '+93.222s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 7, 'grid' => 8, 'laps' => 58, 'time_or_retired' => '+95.601s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 8, 'grid' => 9, 'laps' => 58, 'time_or_retired' => '+100.992s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 9, 'grid' => 10, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 10, 'grid' => 11, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 11, 'grid' => 12, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 12, 'grid' => 13, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 13, 'grid' => 14, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 14, 'grid' => 15, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 15, 'grid' => 16, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 16, 'grid' => 17, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 7, 'constructor_id' => 3, 'position' => null, 'grid' => 19, 'laps' => 56, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 8, 'constructor_id' => 3, 'position' => null, 'grid' => 20, 'laps' => 15, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 3, 'driver_id' => 1, 'constructor_id' => 1, 'position' => null, 'grid' => 1, 'laps' => 3, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 4, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 1, 'grid' => 1, 'laps' => 53, 'time_or_retired' => '1:54:23.566', 'points' => 26.0, 'fastest_lap' => true],
            ['grand_prix_id' => 4, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 2, 'grid' => 2, 'laps' => 53, 'time_or_retired' => '+12.535s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 3, 'grid' => 4, 'laps' => 53, 'time_or_retired' => '+20.866s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 4, 'grid' => 8, 'laps' => 53, 'time_or_retired' => '+26.522s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 5, 'grid' => 3, 'laps' => 53, 'time_or_retired' => '+29.700s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 6, 'grid' => 5, 'laps' => 53, 'time_or_retired' => '+44.272s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 7, 'grid' => 9, 'laps' => 53, 'time_or_retired' => '+45.951s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 8, 'grid' => 6, 'laps' => 53, 'time_or_retired' => '+47.525s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 9, 'grid' => 7, 'laps' => 53, 'time_or_retired' => '+48.626s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 10, 'grid' => 10, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 11, 'grid' => 12, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 12, 'grid' => 16, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 13, 'grid' => 18, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 14, 'grid' => 13, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 15, 'grid' => 15, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 16, 'grid' => 17, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 17, 'grid' => 19, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 15, 'constructor_id' => 9, 'position' => null, 'grid' => 20, 'laps' => 12, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 20, 'constructor_id' => 8, 'position' => null, 'grid' => 11, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 4, 'driver_id' => 18, 'constructor_id' => 7, 'position' => null, 'grid' => 14, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 5, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 1, 'grid' => 1, 'laps' => 56, 'time_or_retired' => '1:40:52.554', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 2, 'grid' => 4, 'laps' => 56, 'time_or_retired' => '+13.773s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 3, 'grid' => 2, 'laps' => 56, 'time_or_retired' => '+19.160s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 4, 'grid' => 6, 'laps' => 56, 'time_or_retired' => '+23.623s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 5, 'grid' => 7, 'laps' => 56, 'time_or_retired' => '+33.983s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 6, 'grid' => 8, 'laps' => 56, 'time_or_retired' => '+38.724s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 7, 'grid' => 3, 'laps' => 56, 'time_or_retired' => '+43.414s', 'points' => 7.0, 'fastest_lap' => true],
            ['grand_prix_id' => 5, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 8, 'grid' => 5, 'laps' => 56, 'time_or_retired' => '+56.198s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 9, 'grid' => 18, 'laps' => 56, 'time_or_retired' => '+57.986s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 10, 'grid' => 9, 'laps' => 56, 'time_or_retired' => '+60.476s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 11, 'grid' => 13, 'laps' => 56, 'time_or_retired' => '+62.812s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 12, 'grid' => 14, 'laps' => 56, 'time_or_retired' => '+65.506s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 13, 'grid' => 15, 'laps' => 56, 'time_or_retired' => '+69.223s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 14, 'grid' => 16, 'laps' => 56, 'time_or_retired' => '+71.689s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 15, 'grid' => 11, 'laps' => 56, 'time_or_retired' => '+82.786s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 16, 'grid' => 17, 'laps' => 56, 'time_or_retired' => '+87.533s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 17, 'grid' => 20, 'laps' => 56, 'time_or_retired' => '+95.110s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 20, 'constructor_id' => 8, 'position' => null, 'grid' => 12, 'laps' => 33, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 19, 'constructor_id' => 8, 'position' => null, 'grid' => 19, 'laps' => 26, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 5, 'driver_id' => 16, 'constructor_id' => 9, 'position' => null, 'grid' => 10, 'laps' => 19, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 6, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 1, 'grid' => 5, 'laps' => 57, 'time_or_retired' => '1:30:49.876', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 2, 'grid' => 1, 'laps' => 57, 'time_or_retired' => '+7.612s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 3, 'grid' => 2, 'laps' => 57, 'time_or_retired' => '+9.920s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 4, 'grid' => 4, 'laps' => 57, 'time_or_retired' => '+14.650s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 5, 'grid' => 3, 'laps' => 57, 'time_or_retired' => '+16.407s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 6, 'grid' => 8, 'laps' => 57, 'time_or_retired' => '+16.585s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 7, 'grid' => 10, 'laps' => 57, 'time_or_retired' => '+26.185s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 8, 'grid' => 7, 'laps' => 57, 'time_or_retired' => '+34.789s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 9, 'grid' => 15, 'laps' => 57, 'time_or_retired' => '+37.107s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 10, 'grid' => 13, 'laps' => 57, 'time_or_retired' => '+39.746s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 11, 'grid' => 9, 'laps' => 57, 'time_or_retired' => '+40.789s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 12, 'grid' => 12, 'laps' => 57, 'time_or_retired' => '+44.958s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 13, 'grid' => 6, 'laps' => 57, 'time_or_retired' => '+49.756s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 14, 'grid' => 19, 'laps' => 57, 'time_or_retired' => '+49.979s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 15, 'grid' => 20, 'laps' => 57, 'time_or_retired' => '+50.956s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 16, 'grid' => 16, 'laps' => 57, 'time_or_retired' => '+52.356s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 17, 'grid' => 11, 'laps' => 57, 'time_or_retired' => '+55.173s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 18, 'grid' => 14, 'laps' => 57, 'time_or_retired' => '+76.091s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 19, 'grid' => 18, 'laps' => 57, 'time_or_retired' => '+84.683s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 6, 'driver_id' => 17, 'constructor_id' => 7, 'position' => null, 'grid' => 17, 'laps' => 27, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 7, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 1, 'grid' => 1, 'laps' => 63, 'time_or_retired' => '1:25:25.252', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 2, 'grid' => 2, 'laps' => 63, 'time_or_retired' => '+0.725s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 3, 'grid' => 3, 'laps' => 63, 'time_or_retired' => '+7.916s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 4, 'grid' => 5, 'laps' => 63, 'time_or_retired' => '+14.132s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 5, 'grid' => 4, 'laps' => 63, 'time_or_retired' => '+22.325s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 6, 'grid' => 8, 'laps' => 63, 'time_or_retired' => '+35.104s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 7, 'grid' => 6, 'laps' => 63, 'time_or_retired' => '+47.154s', 'points' => 7.0, 'fastest_lap' => true],
            ['grand_prix_id' => 7, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 8, 'grid' => 11, 'laps' => 63, 'time_or_retired' => '+54.776s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 9, 'grid' => 13, 'laps' => 63, 'time_or_retired' => '+79.556s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 10, 'grid' => 7, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 11, 'grid' => 10, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 12, 'grid' => 18, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 13, 'grid' => 9, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 14, 'grid' => 12, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 15, 'grid' => 17, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 16, 'grid' => 15, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 17, 'grid' => 19, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 18, 'grid' => 16, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 19, 'grid' => 20, 'laps' => 62, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 7, 'driver_id' => 18, 'constructor_id' => 7, 'position' => null, 'grid' => 14, 'laps' => 51, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 8, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 1, 'grid' => 1, 'laps' => 78, 'time_or_retired' => '2:23:15.554', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 2, 'grid' => 2, 'laps' => 78, 'time_or_retired' => '+7.152s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 3, 'grid' => 3, 'laps' => 78, 'time_or_retired' => '+7.585s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 4, 'grid' => 4, 'laps' => 78, 'time_or_retired' => '+8.650s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 5, 'grid' => 5, 'laps' => 78, 'time_or_retired' => '+13.309s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 6, 'grid' => 6, 'laps' => 78, 'time_or_retired' => '+13.853s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 7, 'grid' => 7, 'laps' => 78, 'time_or_retired' => '+14.908s', 'points' => 7.0, 'fastest_lap' => true],
            ['grand_prix_id' => 8, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 8, 'grid' => 8, 'laps' => 77, 'time_or_retired' => '+1 lap', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 9, 'grid' => 9, 'laps' => 77, 'time_or_retired' => '+1 lap', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 10, 'grid' => 10, 'laps' => 77, 'time_or_retired' => '+1 lap', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 11, 'grid' => 14, 'laps' => 76, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 12, 'grid' => 12, 'laps' => 76, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 13, 'grid' => 17, 'laps' => 76, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 14, 'grid' => 13, 'laps' => 76, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 15, 'grid' => 15, 'laps' => 76, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 16, 'grid' => 18, 'laps' => 76, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 12, 'constructor_id' => 6, 'position' => null, 'grid' => 11, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 2, 'constructor_id' => 1, 'position' => null, 'grid' => 16, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 14, 'constructor_id' => 10, 'position' => null, 'grid' => 19, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 8, 'driver_id' => 13, 'constructor_id' => 10, 'position' => null, 'grid' => 20, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 9, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 1, 'grid' => 2, 'laps' => 70, 'time_or_retired' => '1:45:47.927', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 2, 'grid' => 3, 'laps' => 70, 'time_or_retired' => '+3.879s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 3, 'grid' => 1, 'laps' => 70, 'time_or_retired' => '+4.317s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 4, 'grid' => 7, 'laps' => 70, 'time_or_retired' => '+4.915s', 'points' => 13.0, 'fastest_lap' => true],
            ['grand_prix_id' => 9, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 5, 'grid' => 4, 'laps' => 70, 'time_or_retired' => '+10.199s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 6, 'grid' => 6, 'laps' => 70, 'time_or_retired' => '+17.510s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 7, 'grid' => 9, 'laps' => 70, 'time_or_retired' => '+23.625s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 8, 'grid' => 5, 'laps' => 70, 'time_or_retired' => '+28.672s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 9, 'grid' => 15, 'laps' => 70, 'time_or_retired' => '+30.021s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 10, 'grid' => 18, 'laps' => 70, 'time_or_retired' => '+30.313s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 11, 'grid' => 17, 'laps' => 70, 'time_or_retired' => '+30.824s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 12, 'grid' => 14, 'laps' => 70, 'time_or_retired' => '+31.253s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 13, 'grid' => 19, 'laps' => 70, 'time_or_retired' => '+40.487s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 14, 'grid' => 8, 'laps' => 70, 'time_or_retired' => '+52.694s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 15, 'grid' => 20, 'laps' => 69, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 6, 'constructor_id' => 2, 'position' => null, 'grid' => 12, 'laps' => 52, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 18, 'constructor_id' => 7, 'position' => null, 'grid' => 10, 'laps' => 52, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 2, 'constructor_id' => 1, 'position' => null, 'grid' => 16, 'laps' => 51, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 5, 'constructor_id' => 2, 'position' => null, 'grid' => 11, 'laps' => 40, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 9, 'driver_id' => 17, 'constructor_id' => 7, 'position' => null, 'grid' => 13, 'laps' => 23, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 10, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 1, 'grid' => 2, 'laps' => 66, 'time_or_retired' => '1:28:20.227', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 2, 'grid' => 1, 'laps' => 66, 'time_or_retired' => '+2.219s', 'points' => 19.0, 'fastest_lap' => true],
            ['grand_prix_id' => 10, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 3, 'grid' => 3, 'laps' => 66, 'time_or_retired' => '+17.790s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 4, 'grid' => 4, 'laps' => 66, 'time_or_retired' => '+22.320s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 5, 'grid' => 5, 'laps' => 66, 'time_or_retired' => '+22.709s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 6, 'grid' => 6, 'laps' => 66, 'time_or_retired' => '+31.028s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 7, 'grid' => 9, 'laps' => 66, 'time_or_retired' => '+33.760s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 8, 'grid' => 11, 'laps' => 66, 'time_or_retired' => '+59.524s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 9, 'grid' => 7, 'laps' => 66, 'time_or_retired' => '+62.025s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 10, 'grid' => 8, 'laps' => 66, 'time_or_retired' => '+71.889s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 11, 'grid' => 13, 'laps' => 66, 'time_or_retired' => '+79.215s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 12, 'grid' => 10, 'laps' => 65, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 13, 'grid' => 15, 'laps' => 65, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 14, 'grid' => 14, 'laps' => 65, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 15, 'grid' => 18, 'laps' => 65, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 16, 'grid' => 12, 'laps' => 65, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 17, 'grid' => 16, 'laps' => 65, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 18, 'grid' => 20, 'laps' => 65, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 19, 'grid' => 17, 'laps' => 65, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 10, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 20, 'grid' => 19, 'laps' => 64, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 11, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 1, 'grid' => 3, 'laps' => 71, 'time_or_retired' => '1:24:22.798', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 2, 'grid' => 7, 'laps' => 71, 'time_or_retired' => '+1.906s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 3, 'grid' => 4, 'laps' => 71, 'time_or_retired' => '+4.533s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 4, 'grid' => 5, 'laps' => 71, 'time_or_retired' => '+23.142s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 5, 'grid' => 1, 'laps' => 71, 'time_or_retired' => '+37.253s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 6, 'grid' => 9, 'laps' => 71, 'time_or_retired' => '+54.088s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 7, 'grid' => 8, 'laps' => 71, 'time_or_retired' => '+54.672s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 8, 'grid' => 12, 'laps' => 71, 'time_or_retired' => '+60.355s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 9, 'grid' => 11, 'laps' => 71, 'time_or_retired' => '+61.169s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 10, 'grid' => 13, 'laps' => 71, 'time_or_retired' => '+61.766s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 11, 'grid' => 6, 'laps' => 71, 'time_or_retired' => '+67.056s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 12, 'grid' => 10, 'laps' => 71, 'time_or_retired' => '+68.325s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 13, 'grid' => 17, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 14, 'grid' => 14, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 15, 'grid' => 16, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 16, 'grid' => 18, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 17, 'grid' => 17, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 18, 'grid' => 15, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 19, 'grid' => 19, 'laps' => 69, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 11, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 20, 'grid' => 2, 'laps' => 64, 'time_or_retired' => '+7 laps', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 12, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 1, 'grid' => 2, 'laps' => 52, 'time_or_retired' => '1:22:27.059', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 2, 'grid' => 4, 'laps' => 52, 'time_or_retired' => '+1.465s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 3, 'grid' => 3, 'laps' => 52, 'time_or_retired' => '+7.547s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 4, 'grid' => 5, 'laps' => 52, 'time_or_retired' => '+12.429s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 5, 'grid' => 7, 'laps' => 52, 'time_or_retired' => '+47.318s', 'points' => 11.0, 'fastest_lap' => true],
            ['grand_prix_id' => 12, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 6, 'grid' => 6, 'laps' => 52, 'time_or_retired' => '+55.722s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 7, 'grid' => 8, 'laps' => 52, 'time_or_retired' => '+56.569s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 8, 'grid' => 10, 'laps' => 52, 'time_or_retired' => '+63.577s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 9, 'grid' => 9, 'laps' => 52, 'time_or_retired' => '+68.387s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 10, 'grid' => 13, 'laps' => 52, 'time_or_retired' => '+79.303s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 11, 'grid' => 12, 'laps' => 52, 'time_or_retired' => '+88.960s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 12, 'grid' => 17, 'laps' => 52, 'time_or_retired' => '+90.153s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 13, 'grid' => 15, 'laps' => 51, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 14, 'grid' => 11, 'laps' => 51, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 15, 'grid' => 16, 'laps' => 51, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 16, 'grid' => 18, 'laps' => 50, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 17, 'grid' => 19, 'laps' => 50, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 18, 'grid' => 14, 'laps' => 50, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 7, 'constructor_id' => 3, 'position' => null, 'grid' => 1, 'laps' => 33, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 12, 'driver_id' => 11, 'constructor_id' => 6, 'position' => null, 'grid' => 19, 'laps' => 0, 'time_or_retired' => 'DNS', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 13, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 1, 'grid' => 2, 'laps' => 70, 'time_or_retired' => '1:38:01.989', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 2, 'grid' => 1, 'laps' => 70, 'time_or_retired' => '+2.141s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 3, 'grid' => 5, 'laps' => 70, 'time_or_retired' => '+14.880s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 4, 'grid' => 6, 'laps' => 70, 'time_or_retired' => '+19.686s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 5, 'grid' => 3, 'laps' => 70, 'time_or_retired' => '+21.349s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 6, 'grid' => 4, 'laps' => 70, 'time_or_retired' => '+23.073s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 7, 'grid' => 16, 'laps' => 70, 'time_or_retired' => '+39.792s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 8, 'grid' => 17, 'laps' => 70, 'time_or_retired' => '+42.368s', 'points' => 5.0, 'fastest_lap' => true],
            ['grand_prix_id' => 13, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 9, 'grid' => 10, 'laps' => 70, 'time_or_retired' => '+77.259s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 10, 'grid' => 8, 'laps' => 70, 'time_or_retired' => '+77.976s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 11, 'grid' => 7, 'laps' => 70, 'time_or_retired' => '+82.460s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 12, 'grid' => 9, 'laps' => 69, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 13, 'grid' => 11, 'laps' => 69, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 14, 'grid' => 13, 'laps' => 69, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 15, 'grid' => 15, 'laps' => 69, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 16, 'grid' => 12, 'laps' => 69, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 17, 'grid' => 14, 'laps' => 69, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 18, 'grid' => 19, 'laps' => 69, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 19, 'grid' => 18, 'laps' => 69, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 13, 'driver_id' => 11, 'constructor_id' => 6, 'position' => null, 'grid' => 20, 'laps' => 33, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 14, 'driver_id' => 7, 'constructor_id' => 3, 'position' => null, 'grid' => 6, 'laps' => 44, 'time_or_retired' => '1:19:57.040', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 1, 'grid' => 3, 'laps' => 44, 'time_or_retired' => '+0.526s', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 2, 'grid' => 5, 'laps' => 44, 'time_or_retired' => '+1.173s', 'points' => 18.0, 'fastest_lap' => true],
            ['grand_prix_id' => 14, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 3, 'grid' => 1, 'laps' => 44, 'time_or_retired' => '+8.549s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 4, 'grid' => 11, 'laps' => 44, 'time_or_retired' => '+9.226s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 5, 'grid' => 4, 'laps' => 44, 'time_or_retired' => '+9.850s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 6, 'grid' => 7, 'laps' => 44, 'time_or_retired' => '+19.795s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 7, 'grid' => 2, 'laps' => 44, 'time_or_retired' => '+43.195s', 'points' => 7.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 8, 'grid' => 8, 'laps' => 44, 'time_or_retired' => '+49.963s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 9, 'grid' => 9, 'laps' => 44, 'time_or_retired' => '+52.552s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 10, 'grid' => 13, 'laps' => 44, 'time_or_retired' => '+54.926s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 11, 'grid' => 15, 'laps' => 44, 'time_or_retired' => '+63.011s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 12, 'grid' => 10, 'laps' => 44, 'time_or_retired' => '+63.651s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 13, 'grid' => 12, 'laps' => 44, 'time_or_retired' => '+64.365s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 14, 'grid' => 17, 'laps' => 44, 'time_or_retired' => '+66.631s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 15, 'grid' => 14, 'laps' => 44, 'time_or_retired' => '+70.638s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 16, 'grid' => 20, 'laps' => 44, 'time_or_retired' => '+76.737s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 17, 'grid' => 18, 'laps' => 44, 'time_or_retired' => '+86.057s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 18, 'grid' => 16, 'laps' => 44, 'time_or_retired' => '+88.833s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 14, 'driver_id' => 15, 'constructor_id' => 9, 'position' => null, 'grid' => 19, 'laps' => 5, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 15, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 1, 'grid' => 1, 'laps' => 72, 'time_or_retired' => '1:30:45.519', 'points' => 26.0, 'fastest_lap' => true],
            ['grand_prix_id' => 15, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 2, 'grid' => 2, 'laps' => 72, 'time_or_retired' => '+22.896s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 3, 'grid' => 6, 'laps' => 72, 'time_or_retired' => '+25.439s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 4, 'grid' => 3, 'laps' => 72, 'time_or_retired' => '+27.337s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 5, 'grid' => 10, 'laps' => 72, 'time_or_retired' => '+32.137s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 6, 'grid' => 5, 'laps' => 72, 'time_or_retired' => '+39.542s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 7, 'grid' => 4, 'laps' => 72, 'time_or_retired' => '+44.617s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 8, 'grid' => 14, 'laps' => 72, 'time_or_retired' => '+49.599s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 9, 'grid' => 9, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 10, 'grid' => 7, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 11, 'grid' => 12, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 12, 'grid' => 13, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 13, 'grid' => 8, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 14, 'grid' => 19, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 15, 'grid' => 15, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 17, 'constructor_id' => 7, 'position' => 16, 'grid' => 18, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 17, 'grid' => 11, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 18, 'grid' => 20, 'laps' => 71, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 19, 'grid' => 16, 'laps' => 70, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 15, 'driver_id' => 15, 'constructor_id' => 9, 'position' => null, 'grid' => 17, 'laps' => 70, 'time_or_retired' => '+2 laps', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 16, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 1, 'grid' => 4, 'laps' => 53, 'time_or_retired' => '1:14:40.727', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 2, 'grid' => 2, 'laps' => 53, 'time_or_retired' => '+2.664s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 3, 'grid' => 1, 'laps' => 53, 'time_or_retired' => '+6.153s', 'points' => 16.0, 'fastest_lap' => true],
            ['grand_prix_id' => 16, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 4, 'grid' => 5, 'laps' => 53, 'time_or_retired' => '+15.621s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 5, 'grid' => 6, 'laps' => 53, 'time_or_retired' => '+22.820s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 6, 'grid' => 7, 'laps' => 53, 'time_or_retired' => '+37.932s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 7, 'grid' => 3, 'laps' => 53, 'time_or_retired' => '+39.715s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 8, 'grid' => 8, 'laps' => 53, 'time_or_retired' => '+54.148s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 9, 'grid' => 9, 'laps' => 53, 'time_or_retired' => '+67.456s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 10, 'grid' => 13, 'laps' => 53, 'time_or_retired' => '+68.302s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 11, 'grid' => 11, 'laps' => 53, 'time_or_retired' => '+68.495s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 22, 'constructor_id' => 7, 'position' => 12, 'grid' => 18, 'laps' => 53, 'time_or_retired' => '+81.308s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 13, 'grid' => 12, 'laps' => 53, 'time_or_retired' => '+93.452s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 14, 'grid' => 15, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 15, 'grid' => 14, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 16, 'grid' => 19, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 17, 'grid' => 10, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 18, 'grid' => 20, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 19, 'grid' => 17, 'laps' => 52, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 16, 'driver_id' => 19, 'constructor_id' => 8, 'position' => null, 'grid' => 16, 'laps' => 7, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 17, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 1, 'grid' => 2, 'laps' => 51, 'time_or_retired' => '1:32:58.007', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 2, 'grid' => 1, 'laps' => 51, 'time_or_retired' => '+10.910s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 3, 'grid' => 5, 'laps' => 51, 'time_or_retired' => '+31.328s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 4, 'grid' => 15, 'laps' => 51, 'time_or_retired' => '+36.143s', 'points' => 13.0, 'fastest_lap' => true],
            ['grand_prix_id' => 17, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 5, 'grid' => 6, 'laps' => 51, 'time_or_retired' => '+77.098s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 6, 'grid' => 7, 'laps' => 51, 'time_or_retired' => '+85.468s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 7, 'grid' => 9, 'laps' => 51, 'time_or_retired' => '+87.396s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 22, 'constructor_id' => 7, 'position' => 8, 'grid' => 8, 'laps' => 51, 'time_or_retired' => '+89.541s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 9, 'grid' => 19, 'laps' => 51, 'time_or_retired' => '+92.401s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 23, 'constructor_id' => 10, 'position' => 10, 'grid' => 10, 'laps' => 51, 'time_or_retired' => '+93.127s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 11, 'grid' => 12, 'laps' => 51, 'time_or_retired' => '+93.465s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 12, 'grid' => 18, 'laps' => 51, 'time_or_retired' => '+117.189s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 13, 'grid' => 14, 'laps' => 51, 'time_or_retired' => '+146.907s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 14, 'grid' => 17, 'laps' => 51, 'time_or_retired' => '+148.841s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 15, 'grid' => 20, 'laps' => 50, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 16, 'grid' => 16, 'laps' => 50, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 2, 'constructor_id' => 1, 'position' => null, 'grid' => 4, 'laps' => 49, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 6, 'constructor_id' => 2, 'position' => null, 'grid' => 3, 'laps' => 49, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 10, 'constructor_id' => 5, 'position' => null, 'grid' => 13, 'laps' => 45, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 17, 'driver_id' => 19, 'constructor_id' => 8, 'position' => null, 'grid' => 11, 'laps' => 14, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 18, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 1, 'grid' => 1, 'laps' => 62, 'time_or_retired' => '1:40:52.571', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 2, 'grid' => 2, 'laps' => 62, 'time_or_retired' => '+20.945s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 3, 'grid' => 5, 'laps' => 62, 'time_or_retired' => '+41.823s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 4, 'grid' => 4, 'laps' => 62, 'time_or_retired' => '+61.040s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 5, 'grid' => 9, 'laps' => 62, 'time_or_retired' => '+62.430s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 6, 'grid' => 3, 'laps' => 62, 'time_or_retired' => '+85.248s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 7, 'grid' => 10, 'laps' => 62, 'time_or_retired' => '+96.039s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 8, 'grid' => 7, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 9, 'grid' => 6, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 10, 'grid' => 13, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 22, 'constructor_id' => 7, 'position' => 11, 'grid' => 12, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 12, 'grid' => 8, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 13, 'grid' => 15, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 14, 'grid' => 17, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 15, 'grid' => 20, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 16, 'grid' => 19, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 17, 'grid' => 18, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 20, 'constructor_id' => 8, 'position' => 18, 'grid' => 16, 'laps' => 61, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 13, 'constructor_id' => 10, 'position' => null, 'grid' => 14, 'laps' => 57, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 18, 'driver_id' => 18, 'constructor_id' => 7, 'position' => null, 'grid' => 11, 'laps' => 15, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 19, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 1, 'grid' => 4, 'laps' => 56, 'time_or_retired' => '1:35:09.639', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 2, 'grid' => 3, 'laps' => 56, 'time_or_retired' => '+8.562s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 3, 'grid' => 2, 'laps' => 56, 'time_or_retired' => '+19.412s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 4, 'grid' => 1, 'laps' => 56, 'time_or_retired' => '+20.354s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 5, 'grid' => 5, 'laps' => 56, 'time_or_retired' => '+21.921s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 6, 'grid' => 20, 'laps' => 56, 'time_or_retired' => '+56.295s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 7, 'grid' => 9, 'laps' => 56, 'time_or_retired' => '+59.072s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 8, 'grid' => 11, 'laps' => 56, 'time_or_retired' => '+62.957s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 21, 'constructor_id' => 8, 'position' => 9, 'grid' => 19, 'laps' => 56, 'time_or_retired' => '+70.563s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 22, 'constructor_id' => 7, 'position' => 10, 'grid' => 15, 'laps' => 56, 'time_or_retired' => '+71.979s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 11, 'grid' => 8, 'laps' => 56, 'time_or_retired' => '+79.782s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 12, 'grid' => 6, 'laps' => 56, 'time_or_retired' => '+90.558s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 13, 'grid' => 7, 'laps' => 55, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 14, 'grid' => 10, 'laps' => 55, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 15, 'grid' => 13, 'laps' => 55, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 16, 'grid' => 14, 'laps' => 55, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 17, 'grid' => 16, 'laps' => 55, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 18, 'grid' => 12, 'laps' => 55, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 19, 'grid' => 18, 'laps' => 55, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 19, 'driver_id' => 8, 'constructor_id' => 3, 'position' => null, 'grid' => 17, 'laps' => 1, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 20, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 1, 'grid' => 1, 'laps' => 71, 'time_or_retired' => '1:40:55.800', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 2, 'grid' => 3, 'laps' => 71, 'time_or_retired' => '+4.705s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 3, 'grid' => 4, 'laps' => 71, 'time_or_retired' => '+34.387s', 'points' => 16.0, 'fastest_lap' => true],
            ['grand_prix_id' => 20, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 4, 'grid' => 6, 'laps' => 71, 'time_or_retired' => '+44.780s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 5, 'grid' => 5, 'laps' => 71, 'time_or_retired' => '+48.536s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 6, 'grid' => 2, 'laps' => 71, 'time_or_retired' => '+59.558s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 7, 'grid' => 7, 'laps' => 71, 'time_or_retired' => '+63.642s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 8, 'grid' => 17, 'laps' => 71, 'time_or_retired' => '+64.928s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 9, 'grid' => 10, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 10, 'grid' => 8, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 11, 'grid' => 14, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 22, 'constructor_id' => 7, 'position' => 12, 'grid' => 16, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 13, 'grid' => 20, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 14, 'grid' => 15, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 15, 'grid' => 19, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 21, 'constructor_id' => 8, 'position' => 16, 'grid' => 12, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 17, 'grid' => 18, 'laps' => 70, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 9, 'constructor_id' => 5, 'position' => null, 'grid' => 13, 'laps' => 15, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 18, 'constructor_id' => 7, 'position' => null, 'grid' => 9, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 20, 'driver_id' => 19, 'constructor_id' => 8, 'position' => null, 'grid' => 11, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 21, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 1, 'grid' => 17, 'laps' => 69, 'time_or_retired' => '2:06:54.430', 'points' => 26.0, 'fastest_lap' => true],
            ['grand_prix_id' => 21, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 2, 'grid' => 4, 'laps' => 69, 'time_or_retired' => '+19.477s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 3, 'grid' => 13, 'laps' => 69, 'time_or_retired' => '+22.532s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 4, 'grid' => 2, 'laps' => 69, 'time_or_retired' => '+23.265s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 5, 'grid' => 6, 'laps' => 69, 'time_or_retired' => '+30.177s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 6, 'grid' => 1, 'laps' => 69, 'time_or_retired' => '+31.372s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 7, 'grid' => 3, 'laps' => 69, 'time_or_retired' => '+42.056s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 8, 'grid' => 8, 'laps' => 69, 'time_or_retired' => '+44.943s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 21, 'constructor_id' => 8, 'position' => 9, 'grid' => 5, 'laps' => 69, 'time_or_retired' => '+50.452s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 10, 'grid' => 14, 'laps' => 69, 'time_or_retired' => '+50.753s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 11, 'grid' => 12, 'laps' => 69, 'time_or_retired' => '+51.531s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 23, 'constructor_id' => 10, 'position' => 12, 'grid' => 15, 'laps' => 69, 'time_or_retired' => '+57.085s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 13, 'grid' => 11, 'laps' => 69, 'time_or_retired' => '+63.588s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 14, 'grid' => 9, 'laps' => 69, 'time_or_retired' => '+78.049s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 15, 'grid' => 19, 'laps' => 69, 'time_or_retired' => '+79.649s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 6, 'constructor_id' => 2, 'position' => null, 'grid' => 20, 'laps' => 38, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 22, 'constructor_id' => 7, 'position' => null, 'grid' => 16, 'laps' => 30, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 18, 'constructor_id' => 7, 'position' => null, 'grid' => 7, 'laps' => 0, 'time_or_retired' => 'DNS', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 10, 'constructor_id' => 5, 'position' => null, 'grid' => 10, 'laps' => 0, 'time_or_retired' => 'DNS', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 21, 'driver_id' => 14, 'constructor_id' => 10, 'position' => null, 'grid' => 18, 'laps' => 0, 'time_or_retired' => 'DSQ', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 22, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 1, 'grid' => 1, 'laps' => 50, 'time_or_retired' => '1:22:05.969', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 2, 'grid' => 10, 'laps' => 50, 'time_or_retired' => '+7.313s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 3, 'grid' => 2, 'laps' => 50, 'time_or_retired' => '+11.906s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 4, 'grid' => 4, 'laps' => 50, 'time_or_retired' => '+14.283s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 5, 'grid' => 5, 'laps' => 50, 'time_or_retired' => '+16.582s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 6, 'grid' => 6, 'laps' => 50, 'time_or_retired' => '+43.385s', 'points' => 9.0, 'fastest_lap' => true],
            ['grand_prix_id' => 22, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 7, 'grid' => 8, 'laps' => 50, 'time_or_retired' => '+51.365s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 8, 'grid' => 9, 'laps' => 50, 'time_or_retired' => '+59.808s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 9, 'grid' => 7, 'laps' => 50, 'time_or_retired' => '+62.808s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 2, 'constructor_id' => 1, 'position' => 10, 'grid' => 15, 'laps' => 50, 'time_or_retired' => '+63.114s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 11, 'grid' => 16, 'laps' => 50, 'time_or_retired' => '+69.195s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 12, 'grid' => 12, 'laps' => 50, 'time_or_retired' => '+69.803s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 13, 'grid' => 13, 'laps' => 50, 'time_or_retired' => '+74.085s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 22, 'constructor_id' => 7, 'position' => 14, 'grid' => 20, 'laps' => 50, 'time_or_retired' => '+75.172s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 15, 'grid' => 18, 'laps' => 50, 'time_or_retired' => '+84.102s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 21, 'constructor_id' => 8, 'position' => 16, 'grid' => 14, 'laps' => 50, 'time_or_retired' => '+91.005s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 12, 'constructor_id' => 6, 'position' => 17, 'grid' => 11, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 18, 'grid' => 19, 'laps' => 49, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 18, 'constructor_id' => 7, 'position' => null, 'grid' => 17, 'laps' => 25, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 22, 'driver_id' => 11, 'constructor_id' => 6, 'position' => null, 'grid' => 3, 'laps' => 15, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 23, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 1, 'grid' => 2, 'laps' => 57, 'time_or_retired' => '1:31:05.323', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 2, 'grid' => 5, 'laps' => 57, 'time_or_retired' => '+6.031s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 3, 'grid' => 4, 'laps' => 57, 'time_or_retired' => '+6.819s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 4, 'grid' => 1, 'laps' => 57, 'time_or_retired' => '+14.104s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 5, 'grid' => 11, 'laps' => 57, 'time_or_retired' => '+16.782s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 6, 'grid' => 7, 'laps' => 57, 'time_or_retired' => '+17.476s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 7, 'grid' => 8, 'laps' => 57, 'time_or_retired' => '+19.867s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 8, 'grid' => 12, 'laps' => 57, 'time_or_retired' => '+25.360s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 9, 'grid' => 10, 'laps' => 57, 'time_or_retired' => '+32.177s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 10, 'grid' => 3, 'laps' => 57, 'time_or_retired' => '+35.762s', 'points' => 1.0, 'fastest_lap' => true],
            ['grand_prix_id' => 23, 'driver_id' => 16, 'constructor_id' => 9, 'position' => 11, 'grid' => 13, 'laps' => 57, 'time_or_retired' => '+50.243s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 12, 'grid' => 6, 'laps' => 57, 'time_or_retired' => '+56.122s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 13, 'grid' => 14, 'laps' => 57, 'time_or_retired' => '+61.100s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 21, 'constructor_id' => 8, 'position' => 14, 'grid' => 17, 'laps' => 57, 'time_or_retired' => '+62.656s', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 15, 'grid' => 16, 'laps' => 56, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 14, 'constructor_id' => 10, 'position' => null, 'grid' => 18, 'laps' => 39, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 2, 'constructor_id' => 1, 'position' => null, 'grid' => 9, 'laps' => 38, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 10, 'constructor_id' => 5, 'position' => null, 'grid' => 15, 'laps' => 8, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 22, 'constructor_id' => 7, 'position' => null, 'grid' => 19, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 23, 'driver_id' => 12, 'constructor_id' => 6, 'position' => null, 'grid' => 20, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);

        DB::table('race_results')->insert([
            ['grand_prix_id' => 24, 'driver_id' => 3, 'constructor_id' => 4, 'position' => 1, 'grid' => 1, 'laps' => 58, 'time_or_retired' => '1:26:33.291', 'points' => 25.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 6, 'constructor_id' => 2, 'position' => 2, 'grid' => 3, 'laps' => 58, 'time_or_retired' => '+5.832s', 'points' => 18.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 5, 'constructor_id' => 2, 'position' => 3, 'grid' => 19, 'laps' => 58, 'time_or_retired' => '+31.928s', 'points' => 15.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 8, 'constructor_id' => 3, 'position' => 4, 'grid' => 16, 'laps' => 58, 'time_or_retired' => '+36.483s', 'points' => 12.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 7, 'constructor_id' => 3, 'position' => 5, 'grid' => 6, 'laps' => 58, 'time_or_retired' => '+37.538s', 'points' => 10.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 1, 'constructor_id' => 1, 'position' => 6, 'grid' => 4, 'laps' => 58, 'time_or_retired' => '+49.847s', 'points' => 8.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 11, 'constructor_id' => 6, 'position' => 7, 'grid' => 5, 'laps' => 58, 'time_or_retired' => '+72.560s', 'points' => 6.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 14, 'constructor_id' => 10, 'position' => 8, 'grid' => 7, 'laps' => 58, 'time_or_retired' => '+75.554s', 'points' => 4.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 9, 'constructor_id' => 5, 'position' => 9, 'grid' => 8, 'laps' => 58, 'time_or_retired' => '+82.373s', 'points' => 2.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 4, 'constructor_id' => 4, 'position' => 10, 'grid' => 2, 'laps' => 58, 'time_or_retired' => '+83.821s', 'points' => 1.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 18, 'constructor_id' => 7, 'position' => 11, 'grid' => 18, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 19, 'constructor_id' => 8, 'position' => 12, 'grid' => 11, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 15, 'constructor_id' => 9, 'position' => 13, 'grid' => 15, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 10, 'constructor_id' => 5, 'position' => 14, 'grid' => 13, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 24, 'constructor_id' => 6, 'position' => 15, 'grid' => 17, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 13, 'constructor_id' => 10, 'position' => 16, 'grid' => 14, 'laps' => 57, 'time_or_retired' => '+1 lap', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 21, 'constructor_id' => 8, 'position' => null, 'grid' => 12, 'laps' => 55, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 16, 'constructor_id' => 9, 'position' => null, 'grid' => 9, 'laps' => 30, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 22, 'constructor_id' => 7, 'position' => null, 'grid' => 20, 'laps' => 26, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
            ['grand_prix_id' => 24, 'driver_id' => 2, 'constructor_id' => 1, 'position' => null, 'grid' => 10, 'laps' => 0, 'time_or_retired' => 'DNF', 'points' => 0.0, 'fastest_lap' => false],
        ]);
    }
}